[package]
name = "netscape-cookie"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", default-features = false, features = [] }

[dev-dependencies]
curl = "0.4"
tempfile = "3.1"
